"""Brand Voice agent.

Responsible for turning a :class:`CampaignBrief` into a candidate
:class:`CampaignDraft`. Deterministic by default so the system is testable
without an LLM. When ``KINFORM_LLM_PROVIDER=openai`` is set *and*
``openai`` is importable *and* an API key is present, the agent delegates
to the configured model and then re-validates the LLM output through the
same governance pipeline.
"""
from __future__ import annotations

import logging
import os
import re
from typing import Optional

from ..schemas import CTA, CampaignBrief, CampaignDraft
from kinform_shared.governance import (
    BRAND_NAME,
    MAX_CONTENT_CHARS,
    REQUIRED_HASHTAGS,
)

log = logging.getLogger(__name__)

_DEFAULT_CTA_URL = "https://kinform.studio/drops/{slug}"


def _normalise_hashtag(tag: str) -> str:
    tag = tag.strip()
    if not tag:
        return ""
    if not tag.startswith("#"):
        tag = "#" + tag
    return re.sub(r"[^#A-Za-z0-9]+", "", tag)


def _merge_hashtags(extra: list[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    # Required first, in deterministic order.
    for t in REQUIRED_HASHTAGS:
        norm = _normalise_hashtag(t)
        if norm.lower() not in seen:
            seen.add(norm.lower())
            result.append(norm)
    for t in extra:
        norm = _normalise_hashtag(t)
        if norm and norm.lower() not in seen:
            seen.add(norm.lower())
            result.append(norm)
    return result


def _truncate_to_budget(text: str, hashtags: list[str]) -> str:
    """Truncate body so ``body + ' ' + ' '.join(hashtags)`` fits the budget.

    The hashtag line is mandatory, so we trim the body to make room.
    """

    tag_line = " ".join(hashtags)
    # +1 for the joining space; only matters when body is non-empty.
    available = MAX_CONTENT_CHARS - (len(tag_line) + (1 if tag_line else 0))
    if available <= 0:
        # Hashtag line alone exceeds budget — caller's extra_hashtags too big.
        return tag_line[:MAX_CONTENT_CHARS]
    if len(text) > available:
        if available <= 1:
            text = text[:available]
        else:
            text = text[: available - 1].rstrip() + "…"
    return f"{text} {tag_line}".strip() if tag_line else text


def _llm_draft(brief: CampaignBrief) -> Optional[str]:
    """Try the configured LLM; return ``None`` on any failure."""

    provider = os.getenv("KINFORM_LLM_PROVIDER", "").lower()
    if provider != "openai":
        return None
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        return None
    try:  # pragma: no cover — exercised only when an LLM is wired up
        from openai import OpenAI  # type: ignore

        client = OpenAI(api_key=api_key)
        prompt = (
            f"You are the {BRAND_NAME} brand voice. In <= 90 characters, "
            f"write a single line of marketing copy for audience '{brief.audience}' "
            f"about a {brief.product_category}. Confident, quiet-luxury, no emojis. "
            f"Include an imperative verb. Seed: {brief.creative_seed or 'n/a'}."
        )
        resp = client.chat.completions.create(
            model=os.getenv("KINFORM_LLM_MODEL", "gpt-4o-mini"),
            messages=[{"role": "user", "content": prompt}],
            max_tokens=120,
            temperature=0.7,
        )
        return (resp.choices[0].message.content or "").strip()
    except Exception as exc:  # pragma: no cover
        log.warning("LLM draft failed, falling back to deterministic: %s", exc)
        return None


def _deterministic_body(brief: CampaignBrief) -> str:
    """Template-based body. Always includes a CTA verb (``Wear``)."""

    audience = brief.audience.strip().rstrip(".")
    category = brief.product_category.strip().lower()
    return f"Wear the {category}. {audience}, your drop is live."


def generate_draft(brief: CampaignBrief) -> CampaignDraft:
    """Brand Voice entry point. Returns a draft ready for compliance review."""

    body = _llm_draft(brief) or _deterministic_body(brief)
    hashtags = _merge_hashtags(brief.extra_hashtags)
    content = _truncate_to_budget(body, hashtags)

    cta = CTA(
        verb="wear",
        url=_DEFAULT_CTA_URL.format(slug=brief.slug),
        label=f"Wear the {brief.product_category}",
    )
    return CampaignDraft(
        slug=brief.slug,
        title=brief.title,
        content=content,
        hashtags=hashtags,
        cta=cta,
        rationale=(
            f"Generated by Brand Voice agent for audience={brief.audience!r}, "
            f"category={brief.product_category!r}."
        ),
    )
