/**
 * Polymorphic Bootstrapping Compiler.
 *
 * Collects the entire Payload Studio workspace state, serialises it to
 * JSON → Base64, and embeds that payload into a self-contained Python
 * bootstrap script.
 *
 * Guarantees of the generated script:
 *
 *   1. **Idempotent.** Re-running it on a populated directory only writes
 *      files whose SHA-256 differs from disk.
 *   2. **Air-gapped friendly.** Only stdlib imports (`base64`, `json`,
 *      `hashlib`, `pathlib`, `argparse`, `logging`).
 *   3. **Well-logged.** Structured per-file actions and a final summary.
 *   4. **Respects approvals.** Files whose source `approved` flag is False
 *      are written to `<target>/staging/` instead of `<target>/`.
 *   5. **Self-validating.** Embeds the governance rules version and, for
 *      every campaign file, asserts the embedded `rulesVersion` matches.
 *
 * The compiler runs entirely in-browser when invoked from the IDE; the
 * `/api/compile` Next.js route exposes the same function server-side for
 * the GitHub Actions pipeline.
 */

import type { VFS, VFile } from "./vfs";
import { GOVERNANCE_RULES_VERSION } from "@kinform/shared/governance";

/** Settings persisted alongside the workspace. */
export interface CompilerOptions {
  projectName: string;
  /** When true, the script will refuse to run unless every embedded file
   *  is `approved=true`. */
  productionOnly: boolean;
  /** Free-form note shown in the generated header. */
  note?: string;
}

export interface CompilerArtifact {
  filename: string;
  pythonSource: string;
  /** Stats for the IDE to show in a toast. */
  fileCount: number;
  bytes: number;
  rulesVersion: string;
  approvedCount: number;
  unapprovedCount: number;
  generatedAt: string;
}

interface EmbeddedPayload {
  schemaVersion: 1;
  generatedAt: string;
  projectName: string;
  rulesVersion: string;
  productionOnly: boolean;
  note?: string;
  files: Array<{
    path: string;
    kind: VFile["kind"];
    content: string;
    approved: boolean;
    campaignId?: string;
    updatedAt: string;
  }>;
}

function toBase64(s: string): string {
  // Works in both browser (btoa) and Node 18+ (Buffer).
  if (typeof Buffer !== "undefined") {
    return Buffer.from(s, "utf8").toString("base64");
  }
  // browser
  const bytes = new TextEncoder().encode(s);
  let binary = "";
  for (const b of bytes) binary += String.fromCharCode(b);
  // eslint-disable-next-line no-restricted-globals
  return btoa(binary);
}

const PY_TEMPLATE = `#!/usr/bin/env python3
"""KINFORM-AEO bootstrapper — auto-generated by the Payload Studio.

This file is **self-contained**. It uses only the Python standard library
and embeds the entire workspace state as a base64-encoded JSON payload.

Usage:
    python3 {filename} --target ./my-project
    python3 {filename} --target ./my-project --dry-run
    python3 {filename} --target ./my-project --force

It is idempotent: re-runs only rewrite files whose SHA-256 has changed.
Unapproved files are written under '<target>/staging/' so production
artifacts and drafts never co-mingle.
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import json
import logging
import pathlib
import sys
from datetime import datetime, timezone

# --- Embedded payload (do not edit by hand) -----------------------------------
PAYLOAD_B64 = "{payloadB64}"
RULES_VERSION = "{rulesVersion}"
PROJECT_NAME = {projectNameLit}
PRODUCTION_ONLY = {productionOnlyLit}
GENERATED_AT = "{generatedAt}"
# -----------------------------------------------------------------------------

log = logging.getLogger("kinform.bootstrap")


def _decode_payload() -> dict:
    raw = base64.b64decode(PAYLOAD_B64.encode("ascii"))
    return json.loads(raw.decode("utf-8"))


def _sha256(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()


def _write_if_changed(path: pathlib.Path, content: bytes, *, dry_run: bool) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        if _sha256(path.read_bytes()) == _sha256(content):
            return "unchanged"
        action = "updated"
    else:
        action = "created"
    if not dry_run:
        path.write_bytes(content)
    return action


def _validate_payload(payload: dict) -> None:
    if payload.get("schemaVersion") != 1:
        raise SystemExit(
            "Payload schemaVersion mismatch — regenerate the bootstrapper."
        )
    if payload.get("rulesVersion") != RULES_VERSION:
        raise SystemExit(
            f"Embedded rules version mismatch: payload={payload.get('rulesVersion')!r} "
            f"header={RULES_VERSION!r}"
        )


def _enforce_production(payload: dict) -> None:
    if not PRODUCTION_ONLY:
        return
    bad = [f["path"] for f in payload["files"] if not f.get("approved")]
    if bad:
        joined = "\\n  - ".join(bad)
        raise SystemExit(
            "Refusing to bootstrap: --production-only artifacts must all be "
            f"approved. Unapproved files:\\n  - {joined}"
        )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="KINFORM-AEO bootstrapper")
    parser.add_argument("--target", required=True, type=pathlib.Path,
                        help="Destination directory (will be created).")
    parser.add_argument("--dry-run", action="store_true",
                        help="Plan the writes but do not touch disk.")
    parser.add_argument("--force", action="store_true",
                        help="Allow writes into a non-empty directory.")
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
    )
    started = datetime.now(timezone.utc)
    log.info(
        "KINFORM-AEO bootstrapper starting — project=%s rules=%s generated_at=%s",
        PROJECT_NAME, RULES_VERSION, GENERATED_AT,
    )

    target: pathlib.Path = args.target.resolve()
    if target.exists() and any(target.iterdir()) and not args.force and not args.dry_run:
        raise SystemExit(
            f"Target {target} is not empty. Re-run with --force to allow writes."
        )

    payload = _decode_payload()
    _validate_payload(payload)
    _enforce_production(payload)

    summary = {"created": 0, "updated": 0, "unchanged": 0, "staged": 0}
    for entry in payload["files"]:
        rel = entry["path"].lstrip("/")
        approved = bool(entry.get("approved"))
        out_dir = target if approved else target / "staging"
        out_path = out_dir / rel
        content = entry["content"].encode("utf-8")
        action = _write_if_changed(out_path, content, dry_run=args.dry_run)
        summary[action] = summary.get(action, 0) + 1
        if not approved:
            summary["staged"] += 1
        log.info("%-9s %s%s", action, out_path, " (staged)" if not approved else "")

    log.info(
        "Done in %.2fs — %s",
        (datetime.now(timezone.utc) - started).total_seconds(),
        json.dumps(summary, sort_keys=True),
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
`;

function pyRepr(s: string): string {
  // JSON-encoded strings are valid Python string literals.
  return JSON.stringify(s);
}

/** Compile the workspace into a runnable Python bootstrap script. */
export function compile(vfs: VFS, opts: CompilerOptions): CompilerArtifact {
  const now = new Date();
  const payload: EmbeddedPayload = {
    schemaVersion: 1,
    generatedAt: now.toISOString(),
    projectName: opts.projectName,
    rulesVersion: GOVERNANCE_RULES_VERSION,
    productionOnly: opts.productionOnly,
    note: opts.note,
    files: vfs.files.map((f) => ({
      path: f.path,
      kind: f.kind,
      content: f.content,
      approved: !!f.approved,
      campaignId: f.campaignId,
      updatedAt: f.updatedAt,
    })),
  };

  const json = JSON.stringify(payload);
  const b64 = toBase64(json);

  const filename = `kinform-bootstrap-${opts.projectName}-${now
    .toISOString()
    .replace(/[:.]/g, "-")}.py`;

  const py = PY_TEMPLATE.replace("{filename}", filename)
    .replace("{payloadB64}", b64)
    .replace("{rulesVersion}", GOVERNANCE_RULES_VERSION)
    .replace("{projectNameLit}", pyRepr(opts.projectName))
    .replace("{productionOnlyLit}", opts.productionOnly ? "True" : "False")
    .replace("{generatedAt}", now.toISOString());

  const approvedCount = payload.files.filter((f) => f.approved).length;
  return {
    filename,
    pythonSource: py,
    fileCount: payload.files.length,
    bytes: py.length,
    rulesVersion: GOVERNANCE_RULES_VERSION,
    approvedCount,
    unapprovedCount: payload.files.length - approvedCount,
    generatedAt: now.toISOString(),
  };
}
